### ISSUE TITLE
Remove -g flag from release build flags

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/native-utils#49]
Adding this flag to 3512's athena release GradleRIO build increases compile times with two threads from 7m 30s to 19m. The state-space libraries are very template-heavy, which generates a lot of debug info.

I suggest that we remove the -g flag from release builds and unconditionally add it to debug builds. Debug info isn't as useful when -O2 optimizations are applied.

**Comment by ThadHouse** [comment]
Solved by 584d236c8688030cc7e98d48d7b458d8ac0dbdae
