### ISSUE TITLE
SourceLinkGenerationTask fails on Windows when Git remote URL uses SSH

### ISSUE THREAD

**Issue by bvisness** [wpilibsuite/native-utils#60]
When building allwpilib on Windows, if the repo was cloned using SSH instead of HTTPS, the SourceLinkGenerationTask fails with "No match found". The issue is the regex match in `resolveSubmodules`, which only supports HTTPS URLs.

I encountered this because I cloned allwpilib through WSL, and used SSH as usual. The SourceLinkGenerationTask only runs on Windows, and I guess most Windows users have always just used HTTPS?

**Comment by ThadHouse** [comment]
Yeah, I know of very few instances where windows clones using ssh. I'll look into seeing what it takes to fix it, but not sure how easy it is, since we do need an https url to make that work. Likely I'll just skip source link if that fails.

**Comment by bvisness** [comment]
As far as I can tell that plugin only cares about the stuff after the URL, so /wpilibsuite/allwpilib.git, which is the same for both.

**Comment by ThadHouse** [comment]
This has been fixed for 2022.
