### ISSUE TITLE
NativePlatforms returns the architecture as 32 bit x86 when running on ARM64

### ISSUE THREAD

**Issue by khari05** [wpilibsuite/native-utils#90]
[NativePlatforms.java#L13](https://github.com/wpilibsuite/native-utils/blob/main/ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/NativePlatforms.java#L13)

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':extractTestJNI'.
> Could not resolve all files for configuration ':nativeDesktopZip'.
   > Could not find opencv-cpp-3.4.7-5-osxx86.zip (edu.wpi.first.thirdparty.frc2021.opencv:opencv-cpp:3.4.7-5).
     Searched in the following locations:
         https://frcmaven.wpi.edu/artifactory/release/edu/wpi/first/thirdparty/frc2021/opencv/opencv-cpp/3.4.7-5/opencv-cpp-3.4.7-5-osxx86.zip
```

[I first noticed this error nearly a year ago](https://github.com/wpilibsuite/allwpilib/issues/3070) when I started using an M1 Macbook Pro. What I noticed was, at the time, the build compiled correctly when running natively. That was because my native Java install was an x86 build of AdoptOpenJDK running in Rosetta 2. It also compiled properly in the WPILib Docker image because Docker automatically emulated it in x86. When I recently updated to using an arm64 build of OpenJDK, that bug that I first noticed in January came back. This time, I traced the cause of the error to `edu.wpi.first.toolchain.NativePlatforms`. `NativePlatforms` is referenced [in the WPILib Gradle extension](https://github.com/wpilibsuite/GradleRIO/blob/main/src/main/java/edu/wpi/first/gradlerio/wpi/WPIExtension.java#L54) which is then called in [the standard build.gradle generated by the wpilib project creator](https://github.com/khari05/FRC-docker-template/blob/master/build.gradle#L48) when downloading C++ dependencies during the Java build.

Temporary Fix:
- Comment out the lines in build.gradle where it downloads packages specific to the desktop platform

Possible Solutions:
- intentionally make the architecture return x86-64 when aarch64/arm64 is detected so that it successfully downloads a file to make gradle happy for now and just warn the user that it is not officially supported
- make arm64 builds of linux (or maybe only Ubuntu) return the platform as `linuxaarch64bionic`
- [add arm64 macOS as a build target?](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary)

Helpful Info:

```
% java --version
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)
```

```groovy
import org.gradle.internal.os.OperatingSystem

println OperatingSystem.current() // Mac OS X 12.0.1 aarch64
println OperatingSystem.current().isMacOsX() // true
println System.getProperty("os.arch") // aarch64
```

**Comment by PeterJohnson** [comment]
We don’t support running arm64 versions of OpenJDK at present.  The WPILib installer installs an x86-64 one.

**Comment by ThadHouse** [comment]
Right now we don't have a plan to support native arm64 Mac for 2022. We're still planning on using an x64 jdk under Rosetta. We plan on investigating this again in 2023

**Comment by khari05** [comment]
I noticed that the bug still occurs on ARM64/AArch64 Linux (a Docker container) where the logic behind `NativePlatforms.desktop` equates AArch64 Linux to 32 bit x86 instead of returning 64 bit ARM even though there are official builds in the maven repository for AArch64 Linux.

**Comment by ThadHouse** [comment]
Right now we don't support any arm platforms as a native desktop build. The aarch64 builds are for cross compilation builds. You'd run into the same issues on a native arm Linux platform. This is something we do want to investigate, but it's a bigger change then we had time to do this season.

**Comment by ThadHouse** [comment]
https://github.com/wpilibsuite/native-utils/pull/105 should fix the linux side of this. Mac was fixed last week.
